### ISSUE TITLE
Is pted_semester_project depricated?

### ISSUE THREAD

**Issue by ratnanil** [zimmewen/Semesterproject#1]
We still have the URL https://github.com/zimmewen/pted_semester_project.git on Moodle, is this URL depricated?

Cheers,

Nils

**Comment by zimmewen** [comment]
Yes it's depricated. Something got mixed up with my local and online files. Created a new repository, the link is on Moodle. But still struggling with uploading files there, as the html seems to be too large. Scheduled a meeting with you on friday for another reason but need to look into that as well.

**Comment by ratnanil** [comment]
if you have time, maybe it would be better to schedule a meeting today? https://calendly.com/rata-zhaw/

**Comment by ratnanil** [comment]
ok, you can close this issue now
