### ISSUE TITLE
Activate Github Pages

### ISSUE THREAD

**Issue by ratnanil** [zimmewen/Semesterproject#3]
I've noticed that you haven't yet activated GitHub Pages on your repo. Can you do this? All you need to do is go to the settings of your repo, go to the tab "Pages" and activate GitHub Pages by choosing your branch (`main` or `master`) and then the folder `root` (see screenshot below). The green box will appear if you click on save.

![gh-pages](https://raw.githubusercontent.com/ComputationalMovementAnalysis/Slides/master/images/gh-pages-2.png)

**Comment by zimmewen** [comment]
Done.
![Unbenannt](https://user-images.githubusercontent.com/104623495/176843095-50651ea8-305c-4c49-9aaa-f6822eccdee9.JPG)
